Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2023-08, with the labels that each got.

#133 [REFACTOR] 학습 목표 타입만 request body에 들어오는 경우 처리
  src/main/java/com/smeme/server/dto/member/MemberPlanUpdateRequestDTO.java
  src/main/java/com/smeme/server/service/MemberService.java
Labels: API, UNAN🐻

#136 [FEAT] 회원 탈퇴 API 개발
  src/main/java/com/smeme/server/controller/AuthController.java
  src/main/java/com/smeme/server/repository/MemberRepository.java
  src/main/java/com/smeme/server/repository/badge/MemberBadgeRepository.java
  src/main/java/com/smeme/server/repository/correction/CorrectionRepository.java
  src/main/java/com/smeme/server/repository/diary/DiaryRepository.java
  src/main/java/com/smeme/server/repository/trainingTime/TrainingTimeRepository.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: API, UNAN🐻

#139 [DOCS] Swagger에 Authorization Header 추가 가능하도록 수정
  src/main/java/com/smeme/server/config/SwaggerConfig.java
  src/main/java/com/smeme/server/controller/AuthController.java
  src/main/java/com/smeme/server/controller/BadgeController.java
  src/main/java/com/smeme/server/controller/CorrectionController.java
  src/main/java/com/smeme/server/controller/DiaryController.java
  src/main/java/com/smeme/server/controller/MemberController.java
  src/main/java/com/smeme/server/controller/TopicController.java
Labels: UNAN🐻, DOCS

#140 [REFACTOR] 소셜로그인, 회원정보 업데이트 API 수정
  src/main/java/com/smeme/server/controller/MemberController.java
  src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
  src/main/java/com/smeme/server/dto/badge/BadgeListResponseDTO.java
  src/main/java/com/smeme/server/dto/member/MemberUpdateRequestDTO.java
  src/main/java/com/smeme/server/dto/member/MemberUpdateResponseDTO.java
  src/main/java/com/smeme/server/model/badge/MemberBadge.java
  src/main/java/com/smeme/server/service/MemberService.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
Labels: REFACTOR, API, UNAN🐻

#141 [CHORE] SiginInRepsonseDTO response body 삭제
  src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
Labels: API, CHORE, UNAN🐻

#143 [REFACTOR] social login api hasPlan 추가
  src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
Labels: API, UNAN🐻

#147 [CHORE] 코드 스타일 통일
  src/main/java/com/smeme/server/controller/AuthController.java
  src/main/java/com/smeme/server/controller/BadgeController.java
  src/main/java/com/smeme/server/controller/BetaAuthController.java
  src/main/java/com/smeme/server/controller/CorrectionController.java
  src/main/java/com/smeme/server/controller/DiaryController.java
  src/main/java/com/smeme/server/controller/TopicController.java
  src/main/java/com/smeme/server/dto/auth/SignInRequestDTO.java
  src/main/java/com/smeme/server/dto/auth/beta/BetaSignInRequestDTO.java
  src/main/java/com/smeme/server/dto/auth/beta/BetaTokenResponseDTO.java
  src/main/java/com/smeme/server/dto/auth/token/TokenResponseDTO.java
  src/main/java/com/smeme/server/dto/auth/token/TokenVO.java
  src/main/java/com/smeme/server/dto/badge/BadgeListResponseDTO.java
  src/main/java/com/smeme/server/dto/badge/BadgeResponseDTO.java
  src/main/java/com/smeme/server/dto/correction/CorrectionResponseDTO.java
  src/main/java/com/smeme/server/dto/diary/CreatedDiaryResponseDTO.java
  src/main/java/com/smeme/server/dto/diary/DiariesResponseDTO.java
  src/main/java/com/smeme/server/dto/diary/DiaryRequestDTO.java
  src/main/java/com/smeme/server/dto/diary/DiaryResponseDTO.java
  src/main/java/com/smeme/server/dto/goal/GoalsResponseDTO.java
  src/main/java/com/smeme/server/dto/member/MemberGetResponseDTO.java
  src/main/java/com/smeme/server/dto/member/MemberNameResponseDTO.java
  src/main/java/com/smeme/server/dto/member/MemberPlanUpdateRequestDTO.java
  src/main/java/com/smeme/server/dto/member/MemberPushRequestDTO.java
  src/main/java/com/smeme/server/dto/member/MemberUpdateRequestDTO.java
  src/main/java/com/smeme/server/dto/member/MemberUpdateResponseDTO.java
  src/main/java/com/smeme/server/dto/member/UsernameValidator.java
  src/main/java/com/smeme/server/dto/member/ValidUsername.java
  src/main/java/com/smeme/server/dto/message/MessageDTO.java
  src/main/java/com/smeme/server/dto/topic/TopicResponseDTO.java
  src/main/java/com/smeme/server/dto/training/TrainingTimeRequestDTO.java
  src/main/java/com/smeme/server/dto/training/TrainingTimeResponseDTO.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/smeme/server/controller/BadgeControllerTest.java
  src/test/java/com/smeme/server/controller/BetaAuthControllerTest.java
  src/test/java/com/smeme/server/controller/CorrectionControllerTest.java
  src/test/java/com/smeme/server/controller/DiaryControllerTest.java
  src/test/java/com/smeme/server/controller/GoalControllerTest.java
  src/test/java/com/smeme/server/controller/MemberControllerTest.java
Labels: CHORE, SOHYEON 🐣

#150 [ADD] Member 칼럼 추가
  .gitignore
  src/main/java/com/smeme/server/model/Member.java
Labels: ADD, SOHYEON 🐣
