Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2023-05, with the labels that each got.

#47 [CHORE] Swagger3 , Jacoco 세팅
  .gitignore
  build.gradle
  src/main/java/com/smeme/server/config/SecurityConfig.java
  src/test/java/com/smeme/server/SmemeServerRenewalApplicationTests.java
Labels: CHORE

#50 [FEAT] 일기 작성 기능 구현
  build.gradle
  src/main/java/com/smeme/server/config/JpaQueryFactoryConfig.java
  src/main/java/com/smeme/server/controller/DiaryController.java
  src/main/java/com/smeme/server/controller/ErrorHandler.java
  src/main/java/com/smeme/server/dto/diary/DiaryRequestDTO.java
  src/main/java/com/smeme/server/dto/temp
  src/main/java/com/smeme/server/model/Diary.java
  src/main/java/com/smeme/server/model/topic/Category.java
  src/main/java/com/smeme/server/repository/MemberRepository.java
  src/main/java/com/smeme/server/repository/TopicRepository.java
  src/main/java/com/smeme/server/repository/diary/DiaryCustomRepository.java
  src/main/java/com/smeme/server/repository/diary/DiaryRepository.java
  src/main/java/com/smeme/server/repository/diary/DiaryRepositoryImpl.java
  src/main/java/com/smeme/server/repository/temp
  src/main/java/com/smeme/server/service/DiaryService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: SOHYEON 🐣, FEAT

#55 [FEAT] 일기 상세 조회 API 구현
  src/main/java/com/smeme/server/controller/DiaryController.java
  src/main/java/com/smeme/server/dto/diary/DiaryResponseDTO.java
  src/main/java/com/smeme/server/repository/CorrectionRepository.java
  src/main/java/com/smeme/server/service/DiaryService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: SOHYEON 🐣, FEAT

#57 [FEAT] 일기 수정 기능 구현
  src/main/java/com/smeme/server/config/TimezoneConfig.java
  src/main/java/com/smeme/server/controller/DiaryController.java
  src/main/java/com/smeme/server/model/Diary.java
  src/main/java/com/smeme/server/service/DiaryService.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: SOHYEON 🐣, FEAT

#58 [FEAT] 일기 삭제 API 구현
  src/main/java/com/smeme/server/controller/DiaryController.java
  src/main/java/com/smeme/server/controller/ErrorHandler.java
  src/main/java/com/smeme/server/model/Diary.java
  src/main/java/com/smeme/server/repository/diary/DiaryRepositoryImpl.java
  src/main/java/com/smeme/server/service/DiaryService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: SOHYEON 🐣, FEAT

#56 [FEAT] 소셜 로그인 API 구현
  src/main/java/com/smeme/server/config/jwt/JwtTokenFilter.java
  src/main/java/com/smeme/server/config/jwt/JwtTokenProvider.java
  src/main/java/com/smeme/server/controller/AuthController.java
  src/main/java/com/smeme/server/dto/auth/SignInRequestDTO.java
  src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
  src/main/java/com/smeme/server/dto/auth/token/TokenResponseDTO.java
  src/main/java/com/smeme/server/model/Member.java
  src/main/java/com/smeme/server/repository/MemberRepository.java
  src/main/java/com/smeme/server/service/auth/AppleSignIn.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
  src/main/java/com/smeme/server/service/auth/KakaoSignIn.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: API, UNAN🐻

#64 [FEAT] 로그아웃 API 구현
  src/main/java/com/smeme/server/controller/AuthController.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: API, UNAN🐻

#65 [FEAT] 첨삭 기능 구현
  src/main/java/com/smeme/server/controller/CorrectionController.java
  src/main/java/com/smeme/server/controller/DiaryController.java
  src/main/java/com/smeme/server/dto/correction/CorrectionRequestDTO.java
  src/main/java/com/smeme/server/service/CorrectionService.java
  src/main/java/com/smeme/server/util/Util.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: SOHYEON 🐣, FEAT

#68 [FEAT] 첨삭 제거 기능 구현
  src/main/java/com/smeme/server/controller/CorrectionController.java
  src/main/java/com/smeme/server/model/Correction.java
  src/main/java/com/smeme/server/service/CorrectionService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: SOHYEON 🐣, FEAT

#73 [FEAT] 회원가입 (유저정보 설정 API 구현)
  src/main/java/com/smeme/server/controller/ErrorHandler.java
  src/main/java/com/smeme/server/controller/MemberController.java
  src/main/java/com/smeme/server/dto/member/UpdateMemberRequestDTO.java
  src/main/java/com/smeme/server/dto/member/UsernameValidator.java
  src/main/java/com/smeme/server/dto/member/ValidUsername.java
  src/main/java/com/smeme/server/model/Member.java
  src/main/java/com/smeme/server/repository/MemberRepository.java
  src/main/java/com/smeme/server/service/MemberService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: API, UNAN🐻

#75 [FEAT] 첨삭 수정 기능 구현
  src/main/java/com/smeme/server/controller/CorrectionController.java
  src/main/java/com/smeme/server/model/Correction.java
  src/main/java/com/smeme/server/service/CorrectionService.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: SOHYEON 🐣, FEAT

#78 [FIX] 예외 처리 변경
  src/main/java/com/smeme/server/controller/ErrorHandler.java
  src/main/java/com/smeme/server/service/CorrectionService.java
  src/main/java/com/smeme/server/service/DiaryService.java
Labels: SOHYEON 🐣, FIX

#76 [FEAT] 푸시 알림 스케줄러 구현 (매 30분 주기)
  src/main/java/com/smeme/server/controller/MessageController.java
  src/main/java/com/smeme/server/controller/ScheduleController.java
  src/main/java/com/smeme/server/dto/message/MessageRequestDTO.java
  src/main/java/com/smeme/server/model/training/TrainingTime.java
  src/main/java/com/smeme/server/repository/trainingTime/TrainingTimeCustomRepository.java
  src/main/java/com/smeme/server/repository/trainingTime/TrainingTimeRepository.java
  src/main/java/com/smeme/server/repository/trainingTime/TrainingTimeRepositoryImpl.java
  src/main/java/com/smeme/server/service/MessageService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
Labels: SOHYEON 🐣, FEAT

#83 [CHORE] Swagger + RestDocs 통합
  .gitignore
  build.gradle
  src/main/java/com/smeme/server/config/SecurityConfig.java
  src/main/java/com/smeme/server/config/jwt/JwtTokenFilter.java
  src/main/java/com/smeme/server/config/jwt/JwtTokenProvider.java
  src/main/java/com/smeme/server/controller/AuthController.java
  src/main/java/com/smeme/server/controller/ErrorHandler.java
  src/main/java/com/smeme/server/dto/diary/DiariesResponseDTO.java
  src/main/java/com/smeme/server/service/auth/AppleSignInService.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
  src/main/java/com/smeme/server/service/auth/KakaoSignIn.java
  src/main/java/com/smeme/server/service/auth/KakaoSignInService.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/smeme/server/controller/BaseControllerTest.java
  src/test/java/com/smeme/server/controller/TestControllerTest.java
Labels: API, UNAN🐻

#81 [FEAT] 30일 전 삭제된 일기 영구 삭제 스케줄러 구현
  src/main/java/com/smeme/server/controller/ScheduleController.java
  src/main/java/com/smeme/server/model/Diary.java
  src/main/java/com/smeme/server/repository/diary/DiaryCustomRepository.java
  src/main/java/com/smeme/server/repository/diary/DiaryRepositoryImpl.java
  src/main/java/com/smeme/server/service/DiaryService.java
Labels: SOHYEON 🐣, FEAT

#87 [CHORE] exception handler method명 변경
  src/main/java/com/smeme/server/controller/ErrorHandler.java
Labels: UNAN🐻, FEAT

#92 [CHORE] application 파일 정리
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: CHORE, SOHYEON 🐣

#91 [REFACT] 인텔리제이 경고 최소화
  src/main/java/com/smeme/server/config/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/smeme/server/config/jwt/JwtTokenFilter.java
  src/main/java/com/smeme/server/config/jwt/UserAuthentication.java
  src/main/java/com/smeme/server/controller/AuthController.java
  src/main/java/com/smeme/server/controller/MemberController.java
  src/main/java/com/smeme/server/dto/member/ValidUsername.java
  src/main/java/com/smeme/server/model/Diary.java
  src/main/java/com/smeme/server/service/auth/AppleSignInService.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
Labels: REFACTOR, SOHYEON 🐣

#88 [CHORE] 더미데이터 작업
  src/main/java/com/smeme/server/model/badge/BadgeType.java
  src/main/java/com/smeme/server/model/goal/GoalType.java
  src/main/java/com/smeme/server/model/topic/Category.java
Labels: CHORE, SOHYEON 🐣

#89 [FIX] 푸시알람 대상 조회 쿼리 수정
  src/main/java/com/smeme/server/repository/trainingTime/TrainingTimeRepositoryImpl.java
Labels: SOHYEON 🐣, FIX

#93 [REFACTOR] JWT security 관련 로직 수정
  build.gradle
  src/main/java/com/smeme/server/config/SecurityConfig.java
  src/main/java/com/smeme/server/config/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/smeme/server/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/smeme/server/config/jwt/JwtTokenProvider.java
  src/main/java/com/smeme/server/controller/ErrorHandler.java
  src/main/java/com/smeme/server/service/auth/AppleSignInService.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/smeme/server/SmemeServerRenewalApplicationTests.java
  src/test/java/com/smeme/server/controller/BaseControllerTest.java
  src/test/java/com/smeme/server/controller/TestControllerTest.java
Labels: UNAN🐻
