Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2023-07, with the labels that each got.

#119 [REFACTOR] beta test를 위한 API response 개선
  src/main/java/com/smeme/server/controller/BetaAuthController.java
  src/main/java/com/smeme/server/dto/auth/SignInRequestDTO.java
  src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
  src/main/java/com/smeme/server/dto/auth/beta/BetaSignInRequestDTO.java
  src/main/java/com/smeme/server/dto/auth/beta/BetaTokenResponseDTO.java
  src/main/java/com/smeme/server/dto/member/MemberGetResponseDTO.java
  src/main/java/com/smeme/server/dto/member/MemberPushRequestDTO.java
  src/main/java/com/smeme/server/model/Member.java
  src/main/java/com/smeme/server/service/MemberService.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
  src/main/java/com/smeme/server/service/auth/BetaAuthService.java
Labels: API

#122 [FEAT] 푸시 알림 테스트 API
  src/main/java/com/smeme/server/controller/TestController.java
  src/main/java/com/smeme/server/service/MessageService.java
Labels: API, SOHYEON 🐣, FEAT

#124 [REFACTOR] day가 ""로 들어올 경우 학습계획 설정 API 로직 수정
  src/main/java/com/smeme/server/controller/MemberController.java
  src/main/java/com/smeme/server/dto/training/TrainingTimeRequestDTO.java
  src/main/java/com/smeme/server/service/MemberService.java
Labels: REFACTOR, API, UNAN🐻

#127 [FIX] 푸쉬 알림 message 변경
  src/main/java/com/smeme/server/service/MemberService.java
  src/main/java/com/smeme/server/service/MessageService.java
Labels: API, UNAN🐻
