Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2023-02, with the labels that each got.

#8 [FEAT] 일기 작성 기능 구현 및 테스트
  docker-config/docker-compose.yml
  docker-config/init/init.sql
  src/main/java/com/smeme/server/controllers/DiaryController.java
  src/main/java/com/smeme/server/controllers/GlobalControllerAdvice.java
  src/main/java/com/smeme/server/dtos/diary/DiaryCreateRequestDto.java
  src/main/java/com/smeme/server/dtos/diary/DiaryCreateResponseDto.java
  src/main/java/com/smeme/server/models/Category.java
  src/main/java/com/smeme/server/models/Diary.java
  src/main/java/com/smeme/server/models/Social.java
  src/main/java/com/smeme/server/models/Topic.java
  src/main/java/com/smeme/server/models/User.java
  src/main/java/com/smeme/server/repositories/DiaryRepository.java
  src/main/java/com/smeme/server/repositories/TopicRepository.java
  src/main/java/com/smeme/server/repositories/UserRepository.java
  src/main/java/com/smeme/server/services/DiaryService.java
  src/main/java/com/smeme/server/utils/ApiResponse.java
  src/main/resources/application.yml
  src/test/java/com/smeme/server/services/DiaryServiceTest.java
Labels: SOHYEON 🐣, FEAT

#6 [FEAT] Entity 초기 생성
  src/main/java/com/smeme/server/controllers/DiaryController.java
  src/main/java/com/smeme/server/controllers/GlobalControllerAdvice.java
  src/main/java/com/smeme/server/dtos/diary/DiaryCreateRequestDto.java
  src/main/java/com/smeme/server/dtos/diary/DiaryCreateResponseDto.java
  src/main/java/com/smeme/server/models/Category.java
  src/main/java/com/smeme/server/models/Diary.java
  src/main/java/com/smeme/server/models/History.java
  src/main/java/com/smeme/server/models/Like.java
  src/main/java/com/smeme/server/models/Scrap.java
  src/main/java/com/smeme/server/models/Social.java
  src/main/java/com/smeme/server/models/TargetLang.java
  src/main/java/com/smeme/server/models/Topic.java
  src/main/java/com/smeme/server/models/User.java
  src/main/java/com/smeme/server/repositories/DiaryRepository.java
  src/main/java/com/smeme/server/repositories/TopicRepository.java
  src/main/java/com/smeme/server/repositories/UserRepository.java
  src/main/java/com/smeme/server/services/DiaryService.java
  src/main/java/com/smeme/server/utils/ApiResponse.java
  src/main/resources/application.yml
  src/test/java/com/smeme/server/services/DiaryServiceTest.java
Labels: SOHYEON 🐣, FEAT

#12 [FEAT] 게시판 일기 상세조회 기능 구현
  src/main/java/com/smeme/server/controllers/DiaryController.java
  src/main/java/com/smeme/server/dtos/diary/DiaryPublicDetailFindResponseDto.java
  src/main/java/com/smeme/server/services/DiaryService.java
Labels: SOHYEON 🐣, FEAT

#10 [FEAT] 게시판 조회 기능 구현
  src/main/java/com/smeme/server/controllers/DiaryController.java
  src/main/java/com/smeme/server/controllers/GlobalControllerAdvice.java
  src/main/java/com/smeme/server/dtos/diary/DiariesPublicFindResponseDto.java
  src/main/java/com/smeme/server/dtos/diary/DiaryPublicDetailFindResponseDto.java
  src/main/java/com/smeme/server/dtos/diary/DiaryPublicFindRequestDto.java
  src/main/java/com/smeme/server/dtos/diary/DiaryPublicFindResponseDto.java
  src/main/java/com/smeme/server/repositories/CategoryRepository.java
  src/main/java/com/smeme/server/repositories/DiaryRepository.java
  src/main/java/com/smeme/server/repositories/TopicRepository.java
  src/main/java/com/smeme/server/services/DiaryService.java
Labels: SOHYEON 🐣, FEAT

#20 [FEAT] 랜덤 주제 조회 기능 구현
  src/main/java/com/smeme/server/controllers/TopicController.java
  src/main/java/com/smeme/server/dtos/topic/TopicResponseDto.java
  src/main/java/com/smeme/server/services/TopicService.java
Labels: API, SOHYEON 🐣, FEAT

#16 [FEAT] 스크랩 구문 저장 기능 구현
  src/main/java/com/smeme/server/controllers/ScrapController.java
  src/main/java/com/smeme/server/dtos/scrap/ScrapRequestDto.java
  src/main/java/com/smeme/server/dtos/scrap/ScrapResponseDto.java
  src/main/java/com/smeme/server/models/Scrap.java
  src/main/java/com/smeme/server/repositories/ScrapRepository.java
  src/main/java/com/smeme/server/services/ScrapService.java
Labels: API, SOHYEON 🐣, FEAT

#18 [FEAT] 스크랩 리스트 조회 기능 구현
  src/main/java/com/smeme/server/controllers/ScrapController.java
  src/main/java/com/smeme/server/dtos/scrap/ScrapFindRequestDto.java
  src/main/java/com/smeme/server/dtos/scrap/ScrapFindResponseDto.java
  src/main/java/com/smeme/server/dtos/scrap/ScrapsFindResponseDto.java
  src/main/java/com/smeme/server/repositories/ScrapRepository.java
  src/main/java/com/smeme/server/services/ScrapService.java
Labels: API, SOHYEON 🐣, FEAT

#23 [FEAT] 게시판 일기 추천 기능 구현
  src/main/java/com/smeme/server/controllers/DiaryController.java
  src/main/java/com/smeme/server/dtos/diary/DiaryLikeRequestDto.java
  src/main/java/com/smeme/server/dtos/diary/DiaryLikeResponseDto.java
  src/main/java/com/smeme/server/repositories/LikeRepository.java
  src/main/java/com/smeme/server/services/DiaryService.java
Labels: API, SOHYEON 🐣, FEAT

#25 [FEAT] 카테고리 전체 조회 기능 구현
  src/main/java/com/smeme/server/controllers/CategoryController.java
  src/main/java/com/smeme/server/dtos/category/CategoriesResponseDto.java
  src/main/java/com/smeme/server/dtos/category/CategoryResponseDto.java
  src/main/java/com/smeme/server/repositories/CategoryRepository.java
  src/main/java/com/smeme/server/services/CategoryService.java
Labels: API, SOHYEON 🐣, FEAT

#28 [FEAT] 스크랩 삭제 기능 구현
  src/main/java/com/smeme/server/controllers/ScrapController.java
  src/main/java/com/smeme/server/services/ScrapService.java
  src/main/java/com/smeme/server/utils/ApiResponse.java
Labels: API, SOHYEON 🐣, FEAT

#32 [FEAT] 소셜로그인 및 토큰 재발급 API 구현
  .gitignore
  build.gradle
  src/main/java/com/smeme/server/config/SecurityConfig.java
  src/main/java/com/smeme/server/config/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/com/smeme/server/config/jwt/JwtTokenFilter.java
  src/main/java/com/smeme/server/config/jwt/JwtTokenProvider.java
  src/main/java/com/smeme/server/config/jwt/JwtValidationType.java
  src/main/java/com/smeme/server/config/jwt/RestTemplateConfig.java
  src/main/java/com/smeme/server/config/jwt/UserAuthentication.java
  src/main/java/com/smeme/server/controllers/AuthController.java
  src/main/java/com/smeme/server/dtos/auth/AuthGetTokenResponseDto.java
  src/main/java/com/smeme/server/dtos/auth/AuthSignInRequestDto.java
  src/main/java/com/smeme/server/dtos/auth/AuthSignInResponseDto.java
  src/main/java/com/smeme/server/models/User.java
  src/main/java/com/smeme/server/repositories/UserRepository.java
  src/main/java/com/smeme/server/services/AuthService.java
  src/main/resources/application-local.yml
Labels: API, UNAN🐻, FEAT
