Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2023-06, with the labels that each got.

#98 [ADD] 뱃지 획득 로직 추가
  src/main/java/com/smeme/server/controller/CorrectionController.java
  src/main/java/com/smeme/server/controller/DiaryController.java
  src/main/java/com/smeme/server/dto/correction/CorrectionResponseDTO.java
  src/main/java/com/smeme/server/dto/diary/CreatedDiaryResponseDTO.java
  src/main/java/com/smeme/server/repository/MemberBadgeRepository.java
  src/main/java/com/smeme/server/repository/correction/CorrectionCustomRepository.java
  src/main/java/com/smeme/server/repository/correction/CorrectionRepository.java
  src/main/java/com/smeme/server/repository/correction/CorrectionRepositoryImpl.java
  src/main/java/com/smeme/server/repository/diary/DiaryCustomRepository.java
  src/main/java/com/smeme/server/repository/diary/DiaryRepositoryImpl.java
  src/main/java/com/smeme/server/service/BadgeService.java
  src/main/java/com/smeme/server/service/CorrectionService.java
  src/main/java/com/smeme/server/service/DiaryService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
Labels: ADD, SOHYEON 🐣

#99 [ADD] Member 정보 조회 API 구현
  src/main/java/com/smeme/server/controller/MemberController.java
  src/main/java/com/smeme/server/dto/badge/BadgeResponseDTO.java
  src/main/java/com/smeme/server/dto/member/MemberGetResponseDTO.java
  src/main/java/com/smeme/server/dto/member/MemberUpdateRequestDTO.java
  src/main/java/com/smeme/server/dto/training/TrainingTimeResponseDTO.java
  src/main/java/com/smeme/server/repository/trainingTime/TrainingTimeRepository.java
  src/main/java/com/smeme/server/service/BadgeService.java
  src/main/java/com/smeme/server/service/MemberService.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: API, UNAN🐻, ADD

#103 [REFACTOR] BaseTimeEntity 적용 및 그에따른 API 리팩토링
  src/main/java/com/smeme/server/dto/auth/token/TokenVO.java
  src/main/java/com/smeme/server/dto/member/MemberGetResponseDTO.java
  src/main/java/com/smeme/server/model/BaseTimeEntity.java
  src/main/java/com/smeme/server/model/Diary.java
  src/main/java/com/smeme/server/model/Member.java
  src/main/java/com/smeme/server/model/badge/MemberBadge.java
  src/main/java/com/smeme/server/repository/badge/BadgeRepository.java
  src/main/java/com/smeme/server/repository/badge/MemberBadgeRepository.java
  src/main/java/com/smeme/server/repository/goal/GoalRepository.java
  src/main/java/com/smeme/server/service/BadgeService.java
  src/main/java/com/smeme/server/service/CorrectionService.java
  src/main/java/com/smeme/server/service/DiaryService.java
  src/main/java/com/smeme/server/service/MemberService.java
  src/main/java/com/smeme/server/service/auth/AuthService.java
  src/main/java/com/smeme/server/util/message/ErrorMessage.java
Labels: REFACTOR, FEAT

#110 [REFACTOR] 학습 계획 설정 API 개선
  src/main/java/com/smeme/server/service/MemberService.java
Labels: API

#114 [FEAT] 닉네임 중복 검사
  src/main/java/com/smeme/server/config/SecurityConfig.java
  src/main/java/com/smeme/server/controller/MemberController.java
  src/main/java/com/smeme/server/dto/member/MemberNameResponseDTO.java
  src/main/java/com/smeme/server/service/MemberService.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: SOHYEON 🐣, FEAT

#116 [FEAT] 학습 목표 상세 조회
  src/main/java/com/smeme/server/config/SecurityConfig.java
  src/main/java/com/smeme/server/controller/GoalController.java
  src/main/java/com/smeme/server/dto/goal/GoalResponseDTO.java
  src/main/java/com/smeme/server/service/GoalService.java
  src/main/java/com/smeme/server/util/message/ResponseMessage.java
Labels: SOHYEON 🐣, FEAT
