Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2024-04, with the labels that each got.

#249 [ADD] 사이드 요소 추가 및 정리
  README.md
Labels: SOHYEON 🐣

#248 [DOCS] README.md 작성
  README.md
Labels: UNAN🐻, DOCS

#243 [REFACTOR] Service 계층에서 Adapter 계층을 의존하도록 리팩토링
  smeem-api/src/main/java/com/smeem/api/auth/service/AuthService.java
  smeem-api/src/main/java/com/smeem/api/auth/service/TokenService.java
  smeem-api/src/main/java/com/smeem/api/badge/service/BadgeService.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberBadgeService.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/TrainingTimeService.java
  smeem-domain/src/main/java/com/smeem/domain/badge/adapter/BadgeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberDeleter.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberSaver.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberUpdater.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeDeleter.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeSaver.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/trainingtime/TrainingTimeDeleter.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/trainingtime/TrainingTimeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/trainingtime/TrainingTimeSaver.java
  smeem-domain/src/main/java/com/smeem/domain/member/repository/MemberBadgeRepository.java
  smeem-external/src/main/java/com/smeem/external/discord/DiscordAlarmSender.java
Labels: REFACTOR, UNAN🐻

#250 [FIX] 서비스 개요 이미지 수정
  README.md
Labels: SOHYEON 🐣, FIX

#254 [REFACTOR] 어댑터 분리
  smeem-api/src/main/java/com/smeem/api/auth/api/AuthController.java
  smeem-api/src/main/java/com/smeem/api/auth/service/AuthService.java
  smeem-api/src/main/java/com/smeem/api/auth/service/TokenService.java
  smeem-api/src/main/java/com/smeem/api/badge/service/BadgeService.java
  smeem-api/src/main/java/com/smeem/api/diary/service/DiaryCommandService.java
  smeem-api/src/main/java/com/smeem/api/diary/service/DiaryQueryService.java
  smeem-api/src/main/java/com/smeem/api/goal/service/GoalService.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/TrainingTimeService.java
  smeem-api/src/main/java/com/smeem/api/test/service/TestService.java
  smeem-api/src/main/java/com/smeem/api/topic/service/TopicService.java
  smeem-batch/src/main/java/com/smeem/batch/scheduler/DiaryScheduler.java
  smeem-common/src/main/java/com/smeem/common/code/failure/MemberFailureCode.java
  smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java
  smeem-domain/src/main/java/com/smeem/domain/badge/adapter/BadgeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/diary/adapter/DiaryDeleter.java
  smeem-domain/src/main/java/com/smeem/domain/diary/adapter/DiaryFinder.java
  smeem-domain/src/main/java/com/smeem/domain/diary/adapter/DiarySaver.java
  smeem-domain/src/main/java/com/smeem/domain/diary/model/Diary.java
  smeem-domain/src/main/java/com/smeem/domain/goal/adapter/GoalFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberDeleter.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberSaver.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberUpdater.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeDeleter.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeSaver.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/DiaryComboInfo.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/MemberBadge.java
  smeem-domain/src/main/java/com/smeem/domain/support/RepositoryAdapter.java
  smeem-domain/src/main/java/com/smeem/domain/topic/adapter/TopicFinder.java
  smeem-domain/src/main/java/com/smeem/domain/training/adapter/TrainingTimeDeleter.java
  smeem-domain/src/main/java/com/smeem/domain/training/adapter/TrainingTimeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/training/adapter/TrainingTimeSaver.java
Labels: REFACTOR, SOHYEON 🐣

#258 [FEAT] 성과 요약 조회 API
  smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
  smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
  smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberPerformanceGetResponse.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/request/MemberPerformanceGetServiceRequest.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberPerformanceGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/version/api/VersionApi.java
  smeem-common/src/main/java/com/smeem/common/code/success/MemberSuccessCode.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/DiaryComboInfo.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/MemberVisitInfo.java
Labels: SOHYEON 🐣, FEAT

#263 [FIX] 스웨거 토큰 이슈 해결
  smeem-api/src/main/java/com/smeem/api/auth/api/AuthApi.java
  smeem-api/src/main/java/com/smeem/api/badge/api/BadgeApi.java
  smeem-api/src/main/java/com/smeem/api/config/SwaggerConfig.java
  smeem-api/src/main/java/com/smeem/api/diary/api/DiaryApi.java
  smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
  smeem-api/src/main/java/com/smeem/api/test/api/TestApi.java
  smeem-api/src/main/java/com/smeem/api/topic/api/TopicApi.java
Labels: SOHYEON 🐣, FIX

#266 [FEAT] 나의 플랜 조회 API
  smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
  smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
  smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberPlanGetResponse.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/request/MemberPlanGetServiceRequest.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberPlanGetServiceResponse.java
  smeem-common/src/main/java/com/smeem/common/code/success/MemberSuccessCode.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
Labels: API, SOHYEON 🐣, FEAT

#268 [FEAT] 방문 체크 API
  smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
  smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/request/MemberVisitUpdateRequest.java
  smeem-common/src/main/java/com/smeem/common/code/success/MemberSuccessCode.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/MemberVisitInfo.java
Labels: SOHYEON 🐣, FEAT

#267 [FEAT] 플랜 전체 조회 API
  smeem-api/src/main/java/com/smeem/api/config/SecurityConfig.java
  smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
  smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
  smeem-api/src/main/java/com/smeem/api/member/api/dto/request/MemberPlanUpdateRequest.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/request/MemberUpdatePlanServiceRequest.java
  smeem-api/src/main/java/com/smeem/api/plan/api/PlanApi.java
  smeem-api/src/main/java/com/smeem/api/plan/api/PlanController.java
  smeem-api/src/main/java/com/smeem/api/plan/api/dto/response/PlansAllGetResponse.java
  smeem-api/src/main/java/com/smeem/api/plan/service/PlanService.java
  smeem-api/src/main/java/com/smeem/api/plan/service/dto/response/PlansAllGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/support/ExceptionInterceptor.java
  smeem-common/src/main/java/com/smeem/common/code/failure/PlanFailureCode.java
  smeem-common/src/main/java/com/smeem/common/code/success/PlanSuccessCode.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
  smeem-domain/src/main/java/com/smeem/domain/plan/adapter/PlanFinder.java
  smeem-domain/src/main/java/com/smeem/domain/plan/exception/PlanException.java
  smeem-domain/src/main/java/com/smeem/domain/plan/repository/PlanRepository.java
Labels: SOHYEON 🐣, FEAT

#269 [FEAT] 배지 목록 조회 API 구현
  smeem-api/src/main/java/com/smeem/api/badge/api/dto/response/BadgeListResponseV3.java
  smeem-api/src/main/java/com/smeem/api/badge/api/dto/response/BadgeResponseV3.java
  smeem-api/src/main/java/com/smeem/api/badge/api/v2/BadgeV2Api.java
  smeem-api/src/main/java/com/smeem/api/badge/api/v2/BadgeV2Controller.java
  smeem-api/src/main/java/com/smeem/api/badge/api/v3/BadgeV3Api.java
  smeem-api/src/main/java/com/smeem/api/badge/api/v3/BadgeV3Controller.java
  smeem-api/src/main/java/com/smeem/api/badge/service/BadgeService.java
  smeem-api/src/main/java/com/smeem/api/badge/service/dto/request/BadgeListServiceRequestV3.java
  smeem-api/src/main/java/com/smeem/api/badge/service/dto/response/v3/BadgeGetServiceResponseV3.java
  smeem-api/src/main/java/com/smeem/api/badge/service/dto/response/v3/BadgeListServiceResponseV3.java
  smeem-api/src/main/resources/application-dev.yml
  smeem-api/src/main/resources/application-local.yml
  smeem-api/src/main/resources/application-prod.yml
  smeem-batch/src/main/java/com/smeem/batch/scheduler/BadgeScheduler.java
  smeem-batch/src/main/java/com/smeem/batch/scheduler/DiaryScheduler.java
  smeem-batch/src/main/java/com/smeem/batch/scheduler/NotificationScheduler.java
  smeem-batch/src/main/java/com/smeem/batch/scheduler/support/Scheduler.java
  smeem-domain/src/main/java/com/smeem/domain/badge/adapter/BadgeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/badge/adapter/BadgeUpdater.java
  smeem-domain/src/main/java/com/smeem/domain/badge/model/Badge.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberCounter.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeCounter.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/repository/MemberBadgeRepository.java
Labels: API, UNAN🐻, ADD
