Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2024-02, with the labels that each got.

#204 [REFACTOR] 2차 기능 리팩토링
  smeem-api/build.gradle
  smeem-api/src/main/java/com/smeem/api/diary/controller/DiaryController.java
  smeem-api/src/main/java/com/smeem/api/diary/controller/dto/response/DiaryCreateResponse.java
  smeem-api/src/main/java/com/smeem/api/diary/controller/dto/response/DiaryGetResponse.java
  smeem-api/src/main/java/com/smeem/api/diary/controller/dto/response/DiaryListGetResponse.java
  smeem-api/src/main/java/com/smeem/api/diary/service/DiaryCommandService.java
  smeem-api/src/main/java/com/smeem/api/diary/service/DiaryQueryService.java
  smeem-api/src/main/java/com/smeem/api/diary/service/dto/response/DiaryCreateServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/diary/service/dto/response/DiaryGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/diary/service/dto/response/DiaryListGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/goal/controller/GoalController.java
  smeem-api/src/main/java/com/smeem/api/goal/controller/dto/response/GoalGetResponse.java
  smeem-api/src/main/java/com/smeem/api/goal/controller/dto/response/GoalListGetResponse.java
  smeem-api/src/main/java/com/smeem/api/goal/controller/dto/response/GoalListResponse.java
  smeem-api/src/main/java/com/smeem/api/goal/service/GoalService.java
  smeem-api/src/main/java/com/smeem/api/goal/service/dto/request/GoalGetServiceRequest.java
  smeem-api/src/main/java/com/smeem/api/goal/service/dto/response/GoalGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/goal/service/dto/response/GoalListGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/test/controller/TestController.java
  smeem-api/src/main/java/com/smeem/api/test/dto/request/TestPushAlarmRequest.java
  smeem-api/src/main/java/com/smeem/api/test/service/TestService.java
  smeem-api/src/main/java/com/smeem/api/test/service/dto/request/TestPushAlarmServiceRequest.java
  smeem-api/src/main/java/com/smeem/api/topic/controller/TopicController.java
  smeem-api/src/main/java/com/smeem/api/topic/controller/dto/response/RandomTopicGetResponse.java
  smeem-api/src/main/java/com/smeem/api/topic/service/TopicService.java
  smeem-api/src/main/java/com/smeem/api/topic/service/dto/response/RandomTopicGetServiceResponse.java
  smeem-api/src/test/java/com/smeem/api/controller/GoalControllerTest.java
  smeem-api/src/test/java/com/smeem/api/controller/TopicControllerTest.java
  smeem-api/src/test/java/com/smeem/api/fixture/goal/GoalFixture.java
  smeem-api/src/test/java/com/smeem/api/fixture/topic/TopicFixture.java
  smeem-batch/src/main/java/com/smeem/batch/scheduler/MessageScheduler.java
  smeem-common/src/main/java/com/smeem/common/code/failure/TrainingTimeFailureCode.java
  smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java
  smeem-domain/src/main/java/com/smeem/domain/diary/model/DeletedDiary.java
  smeem-domain/src/main/java/com/smeem/domain/diary/model/Diary.java
  smeem-domain/src/main/java/com/smeem/domain/diary/repository/DeletedDiaryRepository.java
  smeem-domain/src/main/java/com/smeem/domain/goal/model/Goal.java
  smeem-domain/src/main/java/com/smeem/domain/goal/model/GoalType.java
  smeem-domain/src/main/java/com/smeem/domain/topic/model/Category.java
  smeem-domain/src/main/java/com/smeem/domain/topic/model/Topic.java
  smeem-domain/src/main/java/com/smeem/domain/training/model/DayType.java
  smeem-domain/src/main/java/com/smeem/domain/training/model/TrainingTime.java
  smeem-external/src/main/java/com/smeem/external/firebase/FcmService.java
  smeem-external/src/main/java/com/smeem/external/firebase/MessageRequest.java
  smeem-external/src/main/java/com/smeem/external/firebase/dto/request/MessagePushRequest.java
  smeem-external/src/main/java/com/smeem/external/firebase/dto/request/MessagePushServiceRequest.java
Labels: REFACTOR, SOHYEON 🐣

#208 [REFACTOR] RestClient 사용 및 그 외
  build.gradle
  smeem-api/src/main/java/com/smeem/api/config/SecurityConfig.java
  smeem-common/src/main/java/com/smeem/common/code/failure/FcmFailureCode.java
  smeem-common/src/main/java/com/smeem/common/exception/FcmException.java
  smeem-external/src/main/java/com/smeem/external/firebase/FcmService.java
Labels: REFACTOR, SOHYEON 🐣

#209 [REFACTOR] 3차 리팩토링 진행
  smeem-api/src/main/java/com/smeem/api/auth/controller/AuthController.java
  smeem-api/src/main/java/com/smeem/api/auth/controller/dto/response/SignInResponse.java
  smeem-api/src/main/java/com/smeem/api/auth/controller/dto/response/token/TokenResponse.java
  smeem-api/src/main/java/com/smeem/api/auth/jwt/JwtAuthenticationFilter.java
  smeem-api/src/main/java/com/smeem/api/auth/jwt/JwtValidationType.java
  smeem-api/src/main/java/com/smeem/api/auth/jwt/TokenProvider.java
  smeem-api/src/main/java/com/smeem/api/auth/jwt/TokenValidator.java
  smeem-api/src/main/java/com/smeem/api/auth/service/AuthService.java
  smeem-api/src/main/java/com/smeem/api/badge/controller/dto/response/AcquiredBadgeResponse.java
  smeem-api/src/main/java/com/smeem/api/badge/controller/dto/response/BadgeBaseResponse.java
  smeem-api/src/main/java/com/smeem/api/badge/controller/dto/response/BadgeListResponse.java
  smeem-api/src/main/java/com/smeem/api/badge/controller/dto/response/BadgeResponse.java
  smeem-api/src/main/java/com/smeem/api/badge/controller/dto/response/BadgeTypeResponse.java
  smeem-api/src/main/java/com/smeem/api/badge/service/BadgeService.java
  smeem-api/src/main/java/com/smeem/api/badge/service/dto/response/BadgeBaseServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/badge/service/dto/response/BadgeListServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/badge/service/dto/response/BadgeTypeServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/common/ApiResponseUtil.java
  smeem-api/src/main/java/com/smeem/api/config/SecurityConfig.java
  smeem-api/src/main/java/com/smeem/api/diary/controller/dto/response/DiaryCreateResponse.java
  smeem-api/src/main/java/com/smeem/api/member/controller/MemberController.java
  smeem-api/src/main/java/com/smeem/api/member/controller/dto/UsernameValidator.java
  smeem-api/src/main/java/com/smeem/api/member/controller/dto/response/MemberGetResponse.java
  smeem-api/src/main/java/com/smeem/api/member/controller/dto/response/MemberNameResponse.java
  smeem-api/src/main/java/com/smeem/api/member/controller/dto/response/MemberUpdateResponse.java
  smeem-api/src/main/java/com/smeem/api/member/controller/dto/response/TrainingTimeResponse.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberBadgeService.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberUpdateServiceResponse.java
  smeem-api/src/test/java/com/smeem/external/oauth/kakao/KakaoServiceTest.java
  smeem-common/src/main/java/com/smeem/common/code/failure/AuthFailureCode.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
  smeem-external/src/main/java/com/smeem/external/oauth/apple/AppleKey.java
  smeem-external/src/main/java/com/smeem/external/oauth/apple/AppleKeyListResponse.java
  smeem-external/src/main/java/com/smeem/external/oauth/apple/AppleService.java
  smeem-external/src/main/java/com/smeem/external/oauth/apple/AppleSignInService.java
  smeem-external/src/main/java/com/smeem/external/oauth/apple/DecodedAppleKey.java
  smeem-external/src/main/java/com/smeem/external/oauth/kakao/KakaoResponse.java
  smeem-external/src/main/java/com/smeem/external/oauth/kakao/KakaoService.java
  smeem-external/src/main/java/com/smeem/external/oauth/kakao/KakaoSignInService.java
Labels: REFACTOR, UNAN🐻

#212 [FIX] jar 파일 경로 수정
  scripts/run_new_was.sh
Labels: SOHYEON 🐣, HOTFIX

#213 [FIX] 테스트 URI 수정
  scripts/health_check.sh
Labels: SOHYEON 🐣, HOTFIX
