Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2024-03, with the labels that each got.

#216 [FIX] Bearer 중복으로 들어가는 코드 삭제
  smeem-external/src/main/java/com/smeem/external/oauth/kakao/KakaoService.java
Labels: BUGFIX, UNAN🐻

#218 [FIX] Member, Badge Controller Response DTO 교체
  smeem-api/src/main/java/com/smeem/api/badge/controller/BadgeController.java
  smeem-api/src/main/java/com/smeem/api/badge/controller/dto/response/BadgeListResponse.java
  smeem-api/src/main/java/com/smeem/api/member/controller/MemberController.java
Labels: BUGFIX, UNAN🐻

#221 [FEAT] Discord 알람 구현
  smeem-api/src/main/java/com/smeem/api/common/advicer/ErrorHandler.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/resources/application-dev.yml
  smeem-api/src/main/resources/application-local.yml
  smeem-api/src/main/resources/application-prod.yml
  smeem-common/src/main/java/com/smeem/common/code/failure/InternalServerFailureCode.java
  smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java
  smeem-external/src/main/java/com/smeem/external/discord/DiscordAlarmCase.java
  smeem-external/src/main/java/com/smeem/external/discord/DiscordAlarmSender.java
  smeem-external/src/main/java/com/smeem/external/discord/DiscordRequest.java
Labels: API, UNAN🐻

#223 [ADD] 목표 제목 추가
  smeem-api/src/main/java/com/smeem/api/goal/controller/dto/response/GoalGetResponse.java
  smeem-api/src/main/java/com/smeem/api/goal/service/dto/response/GoalGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/member/controller/dto/response/MemberGetResponse.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberGetServiceResponse.java
Labels: ADD, SOHYEON 🐣

#229 [CHORE] Auth API implements 키워드 추가
  smeem-api/src/main/java/com/smeem/api/auth/api/AuthApi.java
  smeem-api/src/main/java/com/smeem/api/auth/api/AuthController.java
Labels: API, UNAN🐻

#235 [FEAT] 클라이언트 앱 버전 조회 API
  smeem-api/src/main/java/com/smeem/api/config/SecurityConfig.java
  smeem-api/src/main/java/com/smeem/api/version/api/VersionApi.java
  smeem-api/src/main/java/com/smeem/api/version/api/VersionApiController.java
  smeem-api/src/main/java/com/smeem/api/version/api/dto/response/ClientVersionGetResponse.java
  smeem-api/src/main/java/com/smeem/api/version/service/VersionService.java
  smeem-api/src/main/java/com/smeem/api/version/service/dto/response/ClientVersionGetServiceResponse.java
  smeem-api/src/main/resources/application-dev.yml
  smeem-api/src/main/resources/application-prod.yml
  smeem-common/src/main/java/com/smeem/common/code/success/VersionSuccessCode.java
  smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java
Labels: API, SOHYEON 🐣

#231 [ADD] 스웨거 Response 정보 추가 (제안)
  smeem-api/src/main/java/com/smeem/api/auth/api/AuthApi.java
  smeem-api/src/main/java/com/smeem/api/auth/api/AuthController.java
  smeem-api/src/main/java/com/smeem/api/auth/jwt/CustomJwtAuthenticationEntryPoint.java
  smeem-api/src/main/java/com/smeem/api/badge/api/BadgeApi.java
  smeem-api/src/main/java/com/smeem/api/badge/api/BadgeController.java
  smeem-api/src/main/java/com/smeem/api/common/ApiResponseUtil.java
  smeem-api/src/main/java/com/smeem/api/common/advicer/ErrorHandler.java
  smeem-api/src/main/java/com/smeem/api/common/dto/FailureResponse.java
  smeem-api/src/main/java/com/smeem/api/common/dto/SuccessResponse.java
  smeem-api/src/main/java/com/smeem/api/diary/api/DiaryApi.java
  smeem-api/src/main/java/com/smeem/api/diary/api/DiaryApiController.java
  smeem-api/src/main/java/com/smeem/api/goal/api/GoalApi.java
  smeem-api/src/main/java/com/smeem/api/goal/api/GoalApiController.java
  smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
  smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
  smeem-api/src/main/java/com/smeem/api/test/api/TestApi.java
  smeem-api/src/main/java/com/smeem/api/test/api/TestApiController.java
  smeem-api/src/main/java/com/smeem/api/topic/api/TopicApi.java
  smeem-api/src/main/java/com/smeem/api/topic/api/TopicApiController.java
  smeem-api/src/main/java/com/smeem/api/version/api/VersionApi.java
  smeem-api/src/main/java/com/smeem/api/version/api/VersionApiController.java
  smeem-api/src/main/resources/application-prod.yml
  smeem-api/src/test/java/com/smeem/api/controller/DiaryControllerTest.java
Labels: ADD, SOHYEON 🐣

#241 [HOTFIX] 스케줄러 임시 이동
  smeem-api/src/main/java/com/smeem/api/common/schedulerTemp/DiaryScheduler.java
  smeem-api/src/main/java/com/smeem/api/common/schedulerTemp/MessageScheduler.java
Labels: SOHYEON 🐣, HOTFIX

#239 [REFACTOR] FCM 외부 API 호출 인터페이스 분리 및 기타 리팩토링
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci.yml
  smeem-api/build.gradle
  smeem-api/src/main/java/com/smeem/api/SmemeServerRenewalApplication.java
  smeem-api/src/main/java/com/smeem/api/test/api/TestApi.java
  smeem-api/src/main/java/com/smeem/api/test/api/TestApiController.java
  smeem-api/src/main/java/com/smeem/api/test/service/TestService.java
  smeem-api/src/main/resources/application-dev.yml
  smeem-api/src/main/resources/application-local.yml
  smeem-api/src/main/resources/application-prod.yml
  smeem-batch/src/main/java/com/smeem/batch/scheduler/MessageScheduler.java
  smeem-batch/src/main/java/com/smeem/batch/scheduler/NotificationScheduler.java
  smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java
  smeem-domain/src/main/java/com/smeem/domain/member/repository/MemberCustomRepository.java
  smeem-domain/src/main/java/com/smeem/domain/member/repository/MemberRepository.java
  smeem-domain/src/main/java/com/smeem/domain/member/repository/MemberRepositoryImpl.java
  smeem-domain/src/main/java/com/smeem/domain/training/repository/TrainingTimeCustomRepository.java
  smeem-domain/src/main/java/com/smeem/domain/training/repository/TrainingTimeRepository.java
  smeem-external/src/main/java/com/smeem/external/config/FcmConfig.java
  smeem-external/src/main/java/com/smeem/external/firebase/FcmNotificationService.java
  smeem-external/src/main/java/com/smeem/external/firebase/FcmService.java
  smeem-external/src/main/java/com/smeem/external/firebase/NotificationService.java
  smeem-external/src/main/java/com/smeem/external/firebase/dto/request/MessagePushRequest.java
  smeem-external/src/main/java/com/smeem/external/firebase/dto/request/MessagePushServiceRequest.java
  smeem-external/src/main/java/com/smeem/external/firebase/dto/request/NotificationMulticastRequest.java
  smeem-external/src/main/java/com/smeem/external/firebase/dto/request/NotificationRequest.java
  smeem-external/src/main/java/com/smeem/external/firebase/dto/request/NotificationSingleRequest.java
Labels: REFACTOR, SOHYEON 🐣

#245 [CHORE] Sentry 설정 및 Discord 알람 설정 코드 변경
  smeem-api/build.gradle
  smeem-api/src/main/java/com/smeem/api/support/ExceptionInterceptor.java
  smeem-api/src/main/resources/application-dev.yml
  smeem-api/src/main/resources/application-prod.yml
  smeem-external/src/main/java/com/smeem/external/discord/DiscordAlarmSender.java
Labels: CHORE, UNAN🐻
