Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2024-05, with the labels that each got.

#273 [FIX] 플랜 조회 정렬 조건 추가
  smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
  smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberPerformanceGetResponse.java
  smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberPlanGetResponse.java
  smeem-api/src/main/java/com/smeem/api/plan/api/PlanController.java
  smeem-api/src/main/java/com/smeem/api/plan/api/dto/response/PlansAllGetResponse.java
  smeem-domain/src/main/java/com/smeem/domain/plan/adapter/PlanFinder.java
Labels: SOHYEON 🐣, FIX

#271 [REFACTOR] 사용자 정보 조회 리팩토링
  smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberGetResponse.java
  smeem-api/src/main/java/com/smeem/api/member/api/dto/response/PlanResponse.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/PlanServiceResponse.java
Labels: REFACTOR, API, UNAN🐻

#275 [CHORE] 통합 테스트 환경 세팅
  smeem-api/src/test/java/com/smeem/api/controller/AuthControllerTest.java
  smeem-api/src/test/java/com/smeem/api/controller/BadgeControllerTest.java
  smeem-api/src/test/java/com/smeem/api/controller/BaseControllerTest.java
  smeem-api/src/test/java/com/smeem/api/controller/DiaryControllerTest.java
  smeem-api/src/test/java/com/smeem/api/controller/GoalControllerTest.java
  smeem-api/src/test/java/com/smeem/api/controller/MemberControllerTest.java
  smeem-api/src/test/java/com/smeem/api/controller/TestControllerTest.java
  smeem-api/src/test/java/com/smeem/api/controller/TopicControllerTest.java
  smeem-api/src/test/java/com/smeem/api/fixture/auth/AuthFixture.java
  smeem-api/src/test/java/com/smeem/api/fixture/badge/BadgeFixture.java
  smeem-api/src/test/java/com/smeem/api/fixture/diary/DiaryFixture.java
  smeem-api/src/test/java/com/smeem/api/fixture/goal/GoalFixture.java
  smeem-api/src/test/java/com/smeem/api/fixture/member/MemberFixture.java
  smeem-api/src/test/java/com/smeem/api/fixture/memberbadge/MemberBadgeFixture.java
  smeem-api/src/test/java/com/smeem/api/fixture/topic/TopicFixture.java
  smeem-api/src/test/java/com/smeem/api/fixture/trainingtime/TrainingTimeFixture.java
  smeem-api/src/test/java/com/smeem/external/oauth/kakao/KakaoServiceTest.java
  smeem-api/src/test/java/com/smeem/support/ServiceIntegrationTest.java
  smeem-api/src/test/resources/application-test.yml
Labels: UNAN🐻, SOHYEON 🐣, TEST

#277 [ADD] 학습 플랜 Null 처리 추가
  smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberGetResponse.java
  smeem-api/src/main/java/com/smeem/api/member/api/dto/response/PlanResponse.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberGetServiceResponse.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/PlanServiceResponse.java
Labels: ADD, SOHYEON 🐣

#279 [FIX] 배지 획득 비율 후처리 로직 수정
  smeem-batch/src/main/java/com/smeem/batch/scheduler/BadgeScheduler.java
Labels: UNAN🐻, FIX

#282 [REFACTOR] DiscordAlarmSender -> DiscordService interface로 교체
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/support/ExceptionInterceptor.java
  smeem-external/src/main/java/com/smeem/external/discord/AlarmService.java
  smeem-external/src/main/java/com/smeem/external/discord/DiscordAlarmService.java
Labels: REFACTOR, UNAN🐻

#284 [CHORE] 회원가입 알림 메세지 수정
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java
Labels: CHORE

#286 [DOCS] 리드미 업데이트
  README.md
Labels: SOHYEON 🐣, DOCS

#291 [FIX] 배지 획득까지 남은 횟수 반환 로직 수정
  smeem-api/src/main/java/com/smeem/api/badge/service/BadgeService.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeCounter.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/repository/MemberBadgeRepository.java
Labels: SOHYEON 🐣, FIX

#292 [CHORE] 실서버 배포
  README.md
  smeem-api/src/main/java/com/smeem/api/badge/service/BadgeService.java
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/support/ExceptionInterceptor.java
  smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeCounter.java
  smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeFinder.java
  smeem-domain/src/main/java/com/smeem/domain/member/repository/MemberBadgeRepository.java
  smeem-external/src/main/java/com/smeem/external/discord/AlarmService.java
  smeem-external/src/main/java/com/smeem/external/discord/DiscordAlarmService.java
Labels: SOHYEON 🐣, deploy

#288 [TEST] 일기 저장 관련 테스트 코드 작성
  smeem-api/src/test/java/com/smeem/diary/service/DiaryCommandServiceIntegrationTest.java
  smeem-api/src/test/java/com/smeem/support/ServiceIntegrationTest.java
  smeem-api/src/test/java/com/smeem/support/fixture/MemberFixture.java
  smeem-domain/src/main/java/com/smeem/domain/diary/repository/DiaryRepository.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
Labels: SOHYEON 🐣, TEST

#299 [ADD] 안드로이드 버전 추가
  smeem-api/src/main/java/com/smeem/api/version/service/dto/response/ClientVersionGetServiceResponse.java
  smeem-api/src/main/resources/application-dev.yml
  smeem-api/src/main/resources/application-prod.yml
  smeem-api/src/test/resources/application-test.yml
  smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java
Labels: ADD, SOHYEON 🐣

#300 [ADD] 안드로이드 버전 추가
  smeem-api/src/main/java/com/smeem/api/version/api/dto/response/ClientVersionGetResponse.java
Labels: ADD, SOHYEON 🐣

#302 [REFACTOR] 회원의 방문 이력 테이블 추가
  smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
  smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberPerformanceGetServiceResponse.java
  smeem-api/src/test/java/com/smeem/member/service/MemberServiceIntegrationTest.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
  smeem-domain/src/main/java/com/smeem/domain/member/model/MemberVisitInfo.java
  smeem-domain/src/main/java/com/smeem/domain/visit/adapter/VisitCounter.java
  smeem-domain/src/main/java/com/smeem/domain/visit/adapter/VisitFinder.java
  smeem-domain/src/main/java/com/smeem/domain/visit/adapter/VisitSaver.java
  smeem-domain/src/main/java/com/smeem/domain/visit/model/Visit.java
  smeem-domain/src/main/java/com/smeem/domain/visit/repository/VisitRepository.java
Labels: REFACTOR, SOHYEON 🐣

#306 [HOTFIX] 회원탈퇴 이슈 대응
  smeem-api/src/main/java/com/smeem/api/auth/service/AuthService.java
  smeem-domain/src/main/java/com/smeem/domain/visit/adapter/VisitDeleter.java
  smeem-domain/src/main/java/com/smeem/domain/visit/repository/VisitRepository.java
Labels: SOHYEON 🐣, HOTFIX

#307 [CHORE] 실서버 배포
  smeem-api/src/main/java/com/smeem/api/auth/service/AuthService.java
  smeem-domain/src/main/java/com/smeem/domain/visit/adapter/VisitDeleter.java
  smeem-domain/src/main/java/com/smeem/domain/visit/repository/VisitRepository.java
Labels: SOHYEON 🐣, HOTFIX

#309 [FIX] iOS 버전 업데이트 반영
  smeem-api/src/main/resources/application-dev.yml
  smeem-api/src/main/resources/application-prod.yml
Labels: SOHYEON 🐣, FIX

#310 [FIX] iOS 버전 업데이트
  smeem-api/src/main/resources/application-dev.yml
  smeem-api/src/main/resources/application-prod.yml
Labels: SOHYEON 🐣, FIX
