Repository Team-Smeme/Smeme-server-renewal, pull requests merged in 2025-03, with the labels that each got.

#362 [ADD] added a field in correction response
  smeem-application/src/main/java/com/smeem/application/port/input/dto/response/diary/CorrectionsResponse.java
Labels: add

#366 add: coaching survey api
  smeem-application/src/main/java/com/smeem/application/domain/generic/SmeemMessage.java
  smeem-application/src/main/java/com/smeem/application/domain/survey/CoachingSurvey.java
  smeem-application/src/main/java/com/smeem/application/domain/survey/DissatisfactionType.java
  smeem-application/src/main/java/com/smeem/application/domain/survey/SurveyService.java
  smeem-application/src/main/java/com/smeem/application/port/input/SurveyUseCase.java
  smeem-application/src/main/java/com/smeem/application/port/input/dto/request/survey/CoachingSurveyRequest.java
  smeem-application/src/main/java/com/smeem/application/port/output/persistence/DiaryPort.java
  smeem-application/src/main/java/com/smeem/application/port/output/persistence/SurveyPort.java
  smeem-common/src/main/java/com/smeem/common/exception/ExceptionCode.java
  smeem-input-http/src/main/java/com/smeem/http/controller/SurveyApi.java
  smeem-input-http/src/main/java/com/smeem/http/controller/docs/SurveyApiDocs.java
  smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/GenericEnumListConverter.java
  smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/adapter/DiaryAdapter.java
  smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/adapter/SurveyAdapter.java
  smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/entity/CoachingSurveyEntity.java
  smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/repository/CoachingSurveyRepository.java
Labels: API, add

#368 chore: discord logging for coaching survey
  smeem-application/src/main/java/com/smeem/application/domain/survey/DissatisfactionType.java
  smeem-application/src/main/java/com/smeem/application/domain/survey/SurveyService.java
  smeem-application/src/main/java/com/smeem/application/port/input/dto/request/survey/CoachingSurveyRequest.java
  smeem-common/src/main/java/com/smeem/common/config/DiscordProperties.java
  smeem-common/src/main/java/com/smeem/common/exception/ExceptionCode.java
  smeem-common/src/main/java/com/smeem/common/logger/LoggerType.java
  smeem-common/src/main/java/com/smeem/common/logger/LoggingMessage.java
  smeem-common/src/main/java/com/smeem/common/logger/discord/DiscordHookLogger.java
  smeem-common/src/main/resources/common-config/application-dev.yml
  smeem-common/src/main/resources/common-config/application-local.yml
  smeem-common/src/main/resources/common-config/application-prod.yml
Labels: CHORE, add
